#########################################
#	Vagrantfile for local development	#
#########################################

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Prerequisites:
#	Vagrant and VirtualBox

# Vagrantfile API/syntax version. 
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "ubuntu/trusty32"
	config.vm.provision :shell, path: "build-server-provision.sh"
	config.vm.network "forwarded_port", guest: 80, host: 80
#	config.vm.network "forwarded_port", guest: 8080, host: 8080
end
